@startuml
'https://plantuml.com/class-diagram

class Game

interface RecordDao {
     + doAdd(Record record):void
     + getAllRecords():List<Record>
     + ranking():void
}

RecordDao <. Game
RecordDao <|.. RecordDaoImpl
Record <- RecordDaoImpl

class RecordDaoImpl {
      - records:List<Record>
      + doAdd(Record record):void
      + getAllRecords():List<Record>
      + ranking():void
      + store():void
      + read():void
}

class Record{
      - name:String
      - score:int
      - time:String
      + Record(String time,int score):void
      + getScore():int
      + getName():String
      + getTime():String
      + setName(String name):void
      + setTime(String time):void
      + setScore(int score):void
}
@enduml